version: "3"

services:
    api:
        image: henriquechsf/api-tsnode
        ports:
            - "3030:3001"
        links:
            - link-db
    
    link-db:
        image: tutum/mongodb
        ports:
            - "28017:27017"
        environment:
            - AUTH=no